#Challenge: collect the most gold using all the programming skills you've learned so far!

# Escape from the maze by moving to the X mark.
# Try to collect as many coins as you can.
hero.attack("Treasure Chest")
hero.moveRight()
hero.moveLeft()
hero.moveDown()
hero.moveRight(2)
hero.attack("Gate")
hero.moveRight(2)
hero.moveLeft(2)
hero.moveUp()
hero.moveRight()
hero.moveUp()
hero.moveRight(2)
hero.attack("Cragg")
hero.moveDown(2)
hero.moveUp(2)
hero.moveLeft()
hero.moveUp()
hero.moveRight()
hero.moveUp()
hero.moveRight(2)
hero.attack("Kratt")
hero.moveDown(2)
hero.moveUp(2)
hero.moveLeft()
hero.moveUp()
hero.moveRight()
hero.moveUp()
hero.moveRight(2)
hero.attack("Kog")
hero.moveDown(2)
hero.moveUp(2)
hero.moveLeft()
hero.moveUp()

